In [1]:
import numpy as np #mathematics
import matplotlib.pyplot as plt #like graph plot
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,False,False,False,False,False,False,True,True,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,False,False,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,False,False,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,False,False,False,True,False,True,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,False,False,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,True,False,True,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,False,True,True,False,False,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,True,False,True,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,False,False,False,True,False,False,False

In [6]:
dataset=dataset.astype(int)

In [7]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [8]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [9]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [10]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

dependent=dataset[['classification_yes']]

In [11]:
independent.shape

(399, 27)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [14]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini','entropy','log_loss'],'max_features':['auto','sqrt','log2'], 'splitter':['best','random']}
grid = GridSearchCV( DecisionTreeClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')
grid.fit(x_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.95506713 0.95126635 0.93603222 0.9662661
        nan        nan 0.94015846 0.98125347 0.97725344 0.96995625
        nan        nan 0.94742457 0.94410706 0.93679536 0.97010174]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [15]:
re=grid.cv_results_
grid_predictions=grid.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, grid_predictions)

from sklearn.metrics import classification_report 
clf_report = classification_report(y_test,grid_predictions)

In [16]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'sqrt', 'splitter': 'random'}: 0.9472673583147789

In [17]:
print("The confusion matrix:\n",cm)

The confusion matrix:
 [[47  4]
 [ 3 79]]

In [18]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.94      0.92      0.93        51
           1       0.95      0.96      0.96        82

    accuracy                           0.95       133
   macro avg       0.95      0.94      0.94       133
weighted avg       0.95      0.95      0.95       133

In [19]:
from sklearn.metrics import roc_auc_score 
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.942491630798661

In [20]:
table=pd.DataFrame.from_dict(re)

In [21]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003204,0.003924,0.000000,0.000000,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
1,0.000000,0.000000,0.000000,0.000000,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
2,0.009472,0.007738,0.027134,0.008047,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.944707,0.981014,0.925524,0.962264,0.961826,0.955067,0.018713,6
3,0.006401,0.005988,0.019206,0.003919,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.944707,0.905069,0.925524,0.981031,1.000000,0.951266,0.034931,7
4,0.006402,0.003201,0.023340,0.006336,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.908501,0.903610,0.962573,0.943651,0.961826,0.936032,0.025444,12
5,0.006664,0.003371,0.022610,0.003324,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.944707,0.961755,1.000000,0.943651,0.981217,0.966266,0.021717,5
6,0.001600,0.003200,0.000000,0.000000,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
7,0.003201,0.003920,0.000000,0.000000,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
8,0.006401,0.005988,0.017604,0.003201,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.944707,0.943041,0.888515,0.962264,0.962264,0.940158,0.027105,10
9,0.006402,0.003201,0.017605,0.003200,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.981569,0.962264,1.000000,0.981217,0.981217,0.981253,0.011934,1
10,0.006401,0.005988,0.017604,0.005986,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.961755,0.981217,0.962264,0.981031,0.977253,0.014229,2
11,0.006402,0.003201,0.019205,0.003922,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.981569,0.961755,0.944023,0.981217,0.981217,0.969956,0.015022,4
12,0.003200,0.003919,0.000000,0.000000,log_loss,auto,best,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.001601,0.003202,0.000000,0.000000,log_loss,auto,random,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
14,0.008002,0.005061,0.016003,0.005061,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.981569,0.943041,0.907035,0.943651,0.961826,0.947425,0.024650,8
15,0.009602,0.003198,0.019205,0.003923,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.944707,0.962636,0.944023,0.925146,0.944023,0.944107,0.011859,9
16,0.006404,0.003202,0.020807,0.003917,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",0.908877,0.925272,0.925146,0.981031,0.943651,0.936795,0.024705,11
17,0.006402,0.003201,0.021527,0.004700,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",0.981569,0.943699,0.981217,1.000000,0.944023,0.970102,0.022477,3

In [23]:
age_input=float(input('Age:'))
bp_input=float(input("bp:"))
al_input=float(input("al:"))
su_input=float(input('su:'))
bgr_input=float(input('bgr:'))
bu_input=float(input('bu:'))
sc_input=float(input('sc:'))
sod_input=float(input('sod:'))
pot_input=float(input('pot:'))
hrmo_input=float(input('hrmo:'))
pcv_input=float(input('pcv:'))
wc_input=float(input('wc:'))
rc_input=float(input('rc:'))
sg_b_input=float(input('sg_b:'))
sg_c_input=float(input('sg_c:'))
sg_d_input=float(input('sg_d:'))
sg_e_input=float(input('sg_e:'))
rbc_normal=float(input('rbc_normal:'))
pc_normal=float(input('pc_normal:'))
pcc_present=float(input('pcc_present:'))
ba_present=float(input('ba_present:'))
htn_yes=float(input('htn_yes:'))
dm_yes=float(input('dm_yes:'))
cad_yes=float(input('cad_yes:'))
appet_yes=float(input('appet_yes:'))
pe_yes=float(input('pe_yes:'))
ane_yes=float(input('ane_yes:'))

Age:55
bp:1
al:1
su:1
bgr:1
bu:1
sc:1
sod:1
pot:1
hrmo:1
pcv:1
wc:1
rc:1
sg_b:1
sg_c:1
sg_d:1
sg_e:1
rbc_normal:1
pc_normal:1
pcc_present:1
ba_present:1
htn_yes:1
dm_yes:1
cad_yes:1
appet_yes:1
pe_yes:1
ane_yes:1

In [25]:
Future_prediction=grid.predict([[ age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,
                                 hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,
                                 rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes]])
print("Future_prediction={}".format(Future_prediction))

Future_prediction=[1]